app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('gettable1/',gettable1,name='gettable1'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('gettable2/',gettable2,name='gettable2')
]

project_eight/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),

    path('app1/',include('app1.urls')),

    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def gettable1(request):
    return render(request,'table1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def gettable2(request):
    return render(request,'table2.html')

templates/table1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Table 1</title>
</head>
<body>
    <table border="1" width="50%" cellspace="10" cellpading="100%" align="center"> 
        <tr>
        <th>CSS Property</th>
        <th>Internet Explorer</th>
        <th>FireFox</th>
        <th>Chrome</th>
        <th>Safari</th>
        <th>Opera</th>
        </tr>
        <tr>
            <th>Border Radius</th>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
        </tr>
        <tr>
            <th>Box Sahdow</th>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
        </tr>
        <tr>
            <th>CSS Animations</th>
            <td align="center">NO</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">YES</td>
            <td align="center">NO</td>
        </tr>
    </table>

    <center>
        <a href="{% url 'app2:gettable2' %}">Go to table 2</a>
    </center>
    
</body>
</html>

templates/table2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>TABLE2</title>
</head>
<body>
    <table border="1" width="50%" align="center">
        <tr>
            <th>Product ID</th>
            <th>Product Name</th>
            <th>Product Quality</th>
            <th>Product Quality</th>
        </tr>
        <tr>
            <td align="center">1</td>
            <td align="center">Wheat</td>
            <td align="center">Good</td>
            <td align="center">200 Bags</td>
        </tr>
        <tr>
            <td align="center">2</td>
            <td align="center">Rice</td>
            <td align="center">Good</td>
            <td align="center">250 Bags</td>
        </tr>
        <tr>
            <td align="center">3</td>
            <td align="center">Sugar</td>
            <td align="center">Good</td>
            <td align="center">200 Bags</td>
        </tr>
    </table>

    <center>
        <a href="{% url 'app1:gettable1' %}">Go to table 1</a>
    </center>


</body>
</html>